# Permalinks
permalink:           pretty

# Setup
title:               DevAcument
tagline:             A software developer's judgments and decisions.
url:                 http://devacumen.co.uk
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Andy Nutt
  url:               http://andynutt.co.uk
  email:             

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/AndyRN/devacumen

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
